### ISSUE TITLE
Zmiana położenia info o przeprowadzce do Niemiec w Aktualnościach

### ISSUE THREAD

**Issue by dev999seo** [dev999seo/alan-przeprowadzki.pl#1]
Aktualność powinna być na samym dole listy. Pamiętać żeby grafika nie zasłaniała wpisów!

**Comment by LaaHudra** [comment]
Grafika ok ale jak moze byc najnowsza aktualnośc na samym dole? :dancer:

**Comment by LaaHudra** [comment]
Zrobienio
