### ISSUE TITLE
Zmiany w linkowaniu wewnętrznym

### ISSUE THREAD

**Issue by dev999seo** [dev999seo/alan-przeprowadzki.pl#13]
Usuwamy wszystkie anchory związane z przeprowadzkami do niemiec oraz przeprowadzkami do holandii. Zostają zwykłe linki i do poprawy anchor "blogu" - zwykłe podkreślenie i kolor żółty

**Comment by LaaHudra** [comment]
nie rozumiem zwykle linki to tez anhory

**Comment by LaaHudra** [comment]
link = anhor

**Comment by dev999seo** [comment]
anchor to link z tekstem np. przeprowadzki do holandii a link to link z adresem strony np. http://alan-przeprowadzki.pl/oferta. Wywalamy anchory.
