### ISSUE TITLE
Nie działają znaczniki meta description i meta keywords

### ISSUE THREAD

**Issue by dev999seo** [dev999seo/alan-przeprowadzki.pl#3]
Jak w nagłówku - nie działają / nie wyświetlają się na stronie głównej... i na każdej innej

http://alan-przeprowadzki.pl/oferta

**Comment by LaaHudra** [comment]
meta http-equiv="description" content="Przeprowadzki na Zachód i nie tylko
- Alan" /> <meta http-equiv="keywords" content="przeprowadzki do niemiec,
  przeprowadzki do holandii" />

W dniu 12 listopada 2014 16:18 użytkownik dev999seo <
notifications@github.com> napisał:

**Comment by dev999seo** [comment]
Sprawdź na poważnie te tagi w pages.php bo ani seoquake ani google ich nie widzi po aktualizacji. Może ty je widzisz, ale wyszukiwarka nie widzi.

**Comment by LaaHudra** [comment]
meta http-equiv="description" content="Przeprowadzki międzynarodowe oraz przeprowadzki zagraniczne z doświadczoną i renomowaną firmą. Zapraszamy Państwa do skorzystania z naszych usług!" />
  <meta http-equiv="keywords" content="przeprowadzki międzynarodowe, przeprowadzki zagraniczne, przeprowadzki sulechów, przeprowadzki międzyrzecz" />

**Comment by LaaHudra** [comment]
tagi sa

**Comment by dev999seo** [comment]
OK
