### ISSUE TITLE
Mikroformaty

### ISSUE THREAD

**Issue by dev999seo** [dev999seo/alan-przeprowadzki.pl#7]
Dowiedziałem się, że strony z mikroformatami są lepiej pozycjonowane przez google i zastąpiły Google Authorship. Jeśli umiesz je dodać to zrób to. Poniżej linki z info...
https://support.google.com/webmasters/answer/99170
http://googlewebmastercentral.blogspot.com/2009/05/introducing-rich-snippets.html

**Comment by LaaHudra** [comment]
jak mi powiesz o co chodzi to zrobie :)

**Comment by dev999seo** [comment]
Nie mam pojęcia o tym wiem tylko jak wygląda... Więc rezygnujemy.
