### ISSUE TITLE
Dodać nową aktualność

### ISSUE THREAD

**Issue by dev999seo** [dev999seo/alan-przeprowadzki.pl#8]
Mamy bardzo ciekawe nowości na blogu! Ostatnio umieściliśmu list na temat wybierania dobrej firmy która dokonuje przeprowadzek, są tam wskaźniki, które przydazą się w tym procesie, a również bardzo dobry tekst o cenach przeprowadzek w wielorakim ujęciu w Polsce, jak i poza naszymi granicami na przykładzie <a href="http://alan-przeprowadzki.pl/oferta">przeprowadzki do Holandii</a>. Zapraszamy Was do czytania!

**Comment by dev999seo** [comment]
Oczywiście teskt na blogu z anchorem.

**Comment by dev999seo** [comment]
Oznacz hiperłącze bo w ogóle go nie widać - podkreśl (tak jak przeprowadzki do Niemiec) a hiperłącze do bloga oznacz podobnie i nie zmieniaj koloru czcionki (tylko podkreślone).

**Comment by LaaHudra** [comment]
popawqilem ale nie sraj to dla przegladarki nie musi wygladac zajebiscie

**Comment by LaaHudra** [comment]
nie zdjeles labela resolved
